info:
  contact: {}
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Retrieves data
      produces:
      - application/json
      responses:
        "200":
          description: 'users": []}'
          schema:
            type: string
      summary: Get info about all users
      tags:
      - authentication
    post:
      consumes:
      - application/json
      description: Creates user
      produces:
      - application/json
      responses:
        "200":
          description: 'message": "created user"}'
          schema:
            type: string
      summary: Create user
      tags:
      - authentication
swagger: "2.0"
